# FROM node:8-alpine

# RUN apk update

# RUN npm install -g serverless \
#     npm install -g serverless-offline \
#     npm install -g serverless-bundle \
#     npm install -g serverless-dotenv-plugin \
#     npm install -g serverless-webpack \
#     npm install -g serverless-babel-plugin

# EXPOSE 3000
